/* Server-authoritative school accounts and homework. */
(() => {
 'use strict';
 const ENDPOINT='https://qnhkmasocibvqcedcevm.supabase.co/functions/v1/school-api';
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const titles={igor:'Слово о полку Игореве',liza:'Бедная Лиза',laf:'Лафертовская маковница',gore:'Горе от ума',souls:'Мёртвые души'};
 const games={truth:'Правда или ложь',crossword:'Кроссворд',easy:'Бродилка · лёгкий',medium:'Бродилка · средний',expert:'Бродилка · эксперт'};
 // Расписание литературы: понедельник, среда и четверг, кроме каникулярных недель.
 const vacationWeeks=new Set([6,12,19,26,33]);
 function localDate(value){if(!value)return new Date();if(/^\d{4}-\d{2}-\d{2}$/.test(String(value)))return new Date(`${value}T00:00:00`);const d=new Date(value);return Number.isNaN(d.getTime())?new Date():new Date(d.getFullYear(),d.getMonth(),d.getDate())}
 function lessonDate(value){const d=localDate(value);for(let i=0;i<550;i++,d.setDate(d.getDate()+1)){const y=d.getFullYear(),m=d.getMonth(),schoolYear=m>=8?y:y-1,start=new Date(schoolYear,8,1),end=new Date(schoolYear+1,4,31);if(d<start||d>end)continue;const first=new Date(schoolYear,8,1),week=Math.floor((d-new Date(schoolYear,8,1-((first.getDay()+6)%7)))/604800000)+1;if(vacationWeeks.has(week))continue;if([1,3,4].includes(d.getDay()))return new Date(d.getFullYear(),d.getMonth(),d.getDate())}return d}
 const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const homeworkLesson=h=>{const d=localDate(h.created_at);d.setDate(d.getDate()+1);return dateKey(lessonDate(d))};
 const formatDate=value=>localDate(value).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});
 const classes=['7А','7Б','8А','8Б','9А','9Б'];
 for(const eventName of ['copy','cut','selectstart','contextmenu','dragstart'])document.addEventListener(eventName,e=>e.preventDefault(),true);
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['a','c','x'].includes(e.key.toLowerCase()))e.preventDefault()},true);
 document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});
 document.addEventListener('touchmove',e=>{if(e.touches?.length>1)e.preventDefault()},{passive:false});
 function savedToken(){try{const value=localStorage.getItem('schoolToken')||sessionStorage.getItem('schoolToken')||'';if(value){localStorage.setItem('schoolToken',value);sessionStorage.removeItem('schoolToken')}return value}catch{return sessionStorage.getItem('schoolToken')||''}}
 function saveToken(value){try{localStorage.setItem('schoolToken',value);sessionStorage.removeItem('schoolToken')}catch{sessionStorage.setItem('schoolToken',value)}}
 function clearToken(){try{localStorage.removeItem('schoolToken')}catch{}try{sessionStorage.removeItem('schoolToken')}catch{}}
 let token=savedToken(),user=null,dash=null,attempt=null,busy=false,selectedHW=null,dialog=null,homeworkClass='7А',timerHandle=null,timerDeadline=0,timerExpired=false;
 const staff=()=>user&&user.role!=='student';
 const grade=p=>p>=85?5:p>=70?4:p>=55?3:p>=40?2:p>=25?1:0;
 const options=o=>Object.entries(o).map(([v,t])=>`<option value="${v}">${esc(t)}</option>`).join('');
 const clsOptions=()=>classes.map(c=>`<option>${c}</option>`).join('');
 async function api(action,data={}){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({action,...data})});const json=await r.json();if(!r.ok||json.error)throw new Error(json.error||'Сервис временно недоступен');return json}
 function notice(message){if(dialog?.open){let e=dialog.querySelector('.school-error');if(!e){e=document.createElement('p');e.className='school-error';dialog.append(e)}e.textContent=message}else alert(message)}
 function modal(title,html,extra=''){if(dialog){dialog.close();dialog.remove()}dialog=document.createElement('dialog');dialog.className='school-dialog school-ui '+extra;dialog.innerHTML=`<button class="school-close" aria-label="Закрыть">✕</button><h2>${esc(title)}</h2>${html}<p class="school-error" role="status"></p>`;document.body.append(dialog);dialog.querySelector('.school-close').onclick=()=>dialog.close();dialog.showModal();return dialog}
 function bind(id,fn){$(id).onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{await fn(e)}catch(err){notice(err.message)}finally{b.disabled=false}}}
 function gate(mode='student',message=''){
  document.body.classList.add('school-loading');$('schoolGate')?.remove();const el=document.createElement('section');el.id='schoolGate';el.className='school-gate';
  el.innerHTML=`<div class="school-card"><p class="eyebrow">Игры для учёбы</p><h2>${mode==='register'?'Создать аккаунт ученика':mode==='staff'?'Вход учителя':'Вход ученика'}</h2><p>Литература: читай, играй и узнавай новое.</p><form id="schoolLogin">${mode!=='staff'?'<label>Фамилия<input name="surname" autocomplete="family-name" required maxlength="50"></label><label>Имя<input name="first" autocomplete="given-name" required maxlength="50"></label><label>Класс<select name="class">'+clsOptions()+'</select></label>':''}<label>Пароль<input name="password" type="password" autocomplete="${mode==='register'?'new-password':'current-password'}" required maxlength="128" ${mode==='register'?'minlength="6"':''}></label><button class="primary" type="submit">${mode==='register'?'Зарегистрироваться':'Войти'}</button><p class="school-error" id="loginError" role="status">${esc(message)}</p></form><div class="school-row">${mode!=='student'?'<button data-auth="student">Вход ученика</button>':''}${mode!=='register'?'<button data-auth="register">Регистрация</button>':''}${mode!=='staff'?'<button data-auth="staff">Я учитель</button>':''}</div>${mode==='register'?'<p class="school-muted">Не более 15 учеников в каждом классе. Запомни пароль и не используй пароль от почты.</p>':''}</div>`;
  document.body.append(el);el.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>gate(b.dataset.auth));$('schoolLogin').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;$('loginError').textContent='Подключаемся…';try{const data=Object.fromEntries(new FormData(e.target));const out=await api(mode==='register'?'register':'login',{...data,staff:mode==='staff'});token=out.token;user=out.user;saveToken(token);await enter()}catch(err){$('loginError').textContent=err.message}finally{button.disabled=false}};
 }
 async function hydrate(){await Promise.all(Object.keys(titles).map(async w=>{const d=await api('questions',{work:w});if(w==='igor'){igorTruthFacts.splice(0,igorTruthFacts.length,...d.truthFacts);igorEasyQuiz.splice(0,igorEasyQuiz.length,...d.easyQuiz);igorMediumQuiz.splice(0,igorMediumQuiz.length,...d.mediumQuiz);igorExpertQuiz.splice(0,igorExpertQuiz.length,...d.expertQuiz);igorCrosswordWords.splice(0,igorCrosswordWords.length,...d.crossword)}else Object.assign(w==='liza'?window.LIZA_GAME_DATA:w==='souls'?window.DEAD_SOULS_GAME_DATA:window.EXTRA_GAME_DATA[w],d)}))}
 async function refresh(){dash=await api('dashboard');user=dash.user;locks();return dash}
 async function enter(){await refresh();if(staff())await hydrate();$('schoolGate')?.remove();document.body.classList.remove('school-loading');document.body.classList.toggle('student-mode',!staff());attempt=null;show('home');$('schoolNav')?.remove();const nav=document.createElement('nav');nav.id='schoolNav';nav.className='school-nav school-ui';nav.innerHTML=`<span class="school-name">${esc(user.name)}${user.class?' · '+esc(user.class):''}</span>${staff()?'<button id="schoolQuestions">Вопросы</button><button id="schoolHomework">Домашка</button>':'<button id="schoolMyHomework" class="primary">ДЗ</button>'}<button id="schoolResults">${staff()?'Результаты':'Мои результаты'}</button>${user.role==='admin'?'<button id="schoolAccounts">Аккаунты</button>':''}<button id="schoolPassword">Пароль</button><button id="schoolLogout">Выйти</button>`;$('home').prepend(nav);
  if(staff()){bind('schoolQuestions',questions);bind('schoolHomework',homework)}else bind('schoolMyHomework',studentHomework);if(user.role==='admin')bind('schoolAccounts',accounts);bind('schoolResults',results);bind('schoolPassword',changePassword);bind('schoolLogout',async()=>{try{await api('logout')}finally{token='';clearToken();location.reload()}});
  const cb=document.querySelector('.class-button');if(!staff()){cb.textContent=user.class;cb.setAttribute('aria-label','Открыть задания класса '+user.class);document.querySelector('#works .eyebrow').textContent=user.class+' класс'}locks();
  if(user.role==='student'&&!user.onboarding_done)onboarding();
 }
 function available(w,g){if(!dash)return null;return dash.homework.find(h=>h.active&&h.work===w&&h.game===g&&h.class===user.class)}
 function playable(h){return !!h&&(dash.attempts.some(a=>a.homework_id===h.id&&!a.finished)||dash.attempts.filter(a=>a.homework_id===h.id).length<h.attempts)}
 function locks(){if(!user||staff())return;document.querySelectorAll('[data-work]').forEach(b=>b.classList.toggle('school-locked',!Object.keys(games).some(g=>playable(available(b.dataset.work,g)))));document.querySelectorAll('[data-start]').forEach(b=>{const gs=b.dataset.start==='board'?['easy','medium','expert']:[b.dataset.start];b.classList.toggle('school-locked',!gs.some(g=>playable(available(activeWork,g))))})}
 function locked(b){b.classList.remove('school-shake','school-denied');void b.offsetWidth;b.classList.add('school-shake','school-denied');navigator.vibrate?.([70,35,70]);setTimeout(()=>b.classList.remove('school-shake','school-denied'),750)}
 async function studentHomework(){
  await refresh();const active=dash.homework.filter(h=>h.active&&h.class===user.class);const cards=active.map(h=>{const runs=dash.attempts.filter(a=>a.homework_id===h.id),unfinished=runs.find(a=>!a.finished),finished=runs.filter(a=>a.finished),remaining=Math.max(0,h.attempts-runs.length),best=finished.length?Math.max(...finished.map(a=>Number(a.percent))):null,canPlay=!!unfinished||remaining>0;let status;if(unfinished)status='Начато — можно продолжить';else if(best!==null&&remaining>0)status=`Лучший результат: ${best.toFixed(1)}% · осталось попыток: ${remaining}`;else if(best!==null)status=`Выполнено · результат: ${best.toFixed(1)}%`;else status=`Не начато · попыток: ${remaining}`;return `<article class="school-detail student-hw-card"><div><span class="student-hw-work">${esc(titles[h.work])}</span><h3>${esc(games[h.game])}</h3><p class="student-due-date">Задание к следующему уроку литературы: <b>${esc(formatDate(homeworkLesson(h)))}</b></p><p class="school-muted">${esc(status)}</p></div><button type="button" data-open-homework="${h.id}" class="${canPlay?'primary':''}" ${canPlay?'':'disabled'}>${unfinished?'Продолжить':remaining>0?'Начать':'Готово'}</button></article>`}).join('');const nearest=formatDate(lessonDate(new Date()));const d=modal('Моё ДЗ',`<p class="student-next-lesson">Ближайший урок литературы: <b>${esc(nearest)}</b></p><p class="school-muted">Здесь отображаются задания, которые учитель сейчас открыл для ${esc(user.class)} класса. У каждого задания указана дата урока, к которому оно задано.</p><div id="studentHomeworkList">${cards||'<p class="school-muted hw-empty">Сейчас открытых домашних заданий нет.</p>'}</div>`,'student-homework');d.querySelectorAll('[data-open-homework]').forEach(b=>b.onclick=async()=>{const h=active.find(x=>x.id===b.dataset.openHomework);if(!h||!playable(h)){b.disabled=true;return}selectWork(h.work);await start(h)});
 }
 async function teamGame(){
  await refresh();if(!staff())throw Error('Нет доступа');
  const bank=await api('team_questions');const module=await import('./team-game.js?v=1');
  module.openTeamGame(bank,user);
 }
 window.syncTeamGameTile=work=>{
  $('schoolTeamGame')?.remove();
  if(!staff()||work!=='igor')return;
  const grid=document.querySelector('#book .mode-grid');if(!grid)return;
  const button=document.createElement('button');button.type='button';button.id='schoolTeamGame';button.className='mode';
  button.innerHTML='<span class="mode-icon">⚑</span><span><strong>Своя игра</strong><small>Командная викторина · 2–4 команды</small></span>';
  button.addEventListener('click',()=>teamGame().catch(e=>notice(e.message)));
  grid.append(button);
 };
 async function questions(){const d=modal('Вопросы и ответы',`<div class="school-row"><label>Произведение<select id="sqWork">${options(titles)}</select></label><label>Игра<select id="sqGame">${options(games)}</select></label></div><div id="sqList">Загружаем…</div>`);let seq=0;async function render(){const id=++seq;try{const data=await api('questions',{work:$('sqWork').value});if(id!==seq||!d.open)return;const g=$('sqGame').value;const qs=g==='truth'?data.truthFacts:g==='crossword'?data.crossword:data[g+'Quiz'];$('sqList').innerHTML=qs.map((q,i)=>`<div class="school-detail"><b>${i+1}. ${esc(g==='crossword'?q.clue:q[0])}</b>${g!=='crossword'&&g!=='truth'?'<ol>'+q[1].map(a=>'<li>'+esc(a)+'</li>').join('')+'</ol>':''}<p class="school-answer">Ответ: ${esc(g==='crossword'?q.word:g==='truth'?(q[1]?'Правда':'Ложь'):q[1][q[2]])}</p></div>`).join('')}catch(e){notice(e.message)}}$('sqWork').onchange=render;$('sqGame').onchange=render;await render()}
 async function homework(){await refresh();const d=modal('Домашка',`<p>Выбери класс в строке ниже, чтобы увидеть только его задания. После закрытия доступа задание исчезнет из списка; назначить его снова можно через форму.</p><p>Каждый уровень бродилки — отдельная игра. Каждое новое назначение создаёт отдельную домашку и новый лимит попыток; прошлые результаты сохраняются.</p><form id="hwForm"><div class="school-row"><label>Класс<select name="class">${clsOptions()}</select></label><label>Произведение<select name="work">${options(titles)}</select></label><label>Игра<select name="game">${options(games)}</select></label><label>Попыток<input name="attempts" type="number" min="1" max="100" value="1" required></label></div><button class="primary">Открыть доступ</button><button type="button" id="hwAll">Назначить все 5 игр</button></form><h3>Текущая домашка по классу</h3><div id="hwClasses" class="hw-classes">${classes.map(c=>`<button type="button" data-hw-class="${c}">${c}</button>`).join('')}</div><div id="hwList" aria-live="polite"></div>`);
  $('hwForm').elements.class.value=homeworkClass;
  const renderList=()=>{d.querySelectorAll('[data-hw-class]').forEach(b=>b.classList.toggle('primary',b.dataset.hwClass===homeworkClass));const visible=dash.homework.filter(h=>h.active&&h.class===homeworkClass);$('hwList').innerHTML=visible.map(h=>`<div class="school-detail hw-current"><div><b>${esc(titles[h.work])}</b><span>${esc(games[h.game])} · ${h.attempts} попыт${h.attempts===1?'ка':'ок'}</span></div><button type="button" data-toggle="${h.id}">Закрыть доступ</button></div>`).join('')||'<p class="school-muted hw-empty">Для этого класса сейчас нет открытых заданий.</p>';d.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('toggle',{id:b.dataset.toggle,active:false});await refresh();renderList()}catch(e){notice(e.message);b.disabled=false}})};
  d.querySelectorAll('[data-hw-class]').forEach(b=>b.onclick=()=>{homeworkClass=b.dataset.hwClass;$('hwForm').elements.class.value=homeworkClass;renderList()});renderList();
  $('hwForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const h=Object.fromEntries(new FormData(e.target));homeworkClass=h.class;await api('assign',{...h,attempts:Number(h.attempts)});await refresh();renderList()}catch(err){notice(err.message)}finally{b.disabled=false}};
  bind('hwAll',async()=>{const h=Object.fromEntries(new FormData($('hwForm')));for(const game of Object.keys(games))await api('assign',{...h,game,attempts:Number(h.attempts)});homeworkClass=h.class;await refresh();renderList()});
 }

 function onboarding(){
  const steps=[
   ['Шаг 1 из 3 · Твой класс',`В профиле уже выбран твой класс — <b>${esc(user.class)}</b>. Нажми большую кнопку с классом, чтобы открыть список произведений.`, 'Дальше'],
   ['Шаг 2 из 3 · Выбери игру','Открой нужное произведение и выбери игру: «Правда или ложь», бродилку с уровнем сложности или кроссворд.'],
   ['Шаг 3 из 3 · Нужна домашка','Открой вкладку «ДЗ», чтобы увидеть все текущие задания, количество попыток и сразу начать игру. Играть можно только после того, как учитель назначит домашнее задание твоему классу. Закрытая игра будет серой; нажми на неё, чтобы увидеть красную подсветку.']
  ];let i=0;const d=modal('Как пользоваться сайтом',`<div class="school-detail intro-step"><h3 id="introTitle"></h3><p id="introText"></p></div><div class="school-row"><button class="primary" id="introNext">Дальше</button><button id="introSkip">Понятно, больше не показывать</button></div>`,'school-intro');
  const done=async()=>{try{await api('onboarding_done');user.onboarding_done=true;d.close()}catch(e){notice(e.message)}};
  const paint=()=>{const [title,body,label]=steps[i];$('introTitle').textContent=title;$('introText').innerHTML=body;$('introNext').textContent=label||'Понятно';$('introSkip').hidden=i===steps.length-1};
  $('introNext').onclick=()=>{if(i===steps.length-1)done();else{i++;paint()}};$('introSkip').onclick=done;d.querySelector('.school-close').onclick=done;paint();
 }
 function aggregate(u,homeworks){const cats={board:[],crossword:[],truth:[]};let completed=0,total=0;for(const h of homeworks.filter(h=>h.class===u.class&&h.game!=='expert')){const as=dash.attempts.filter(a=>a.account_id===u.id&&a.homework_id===h.id&&a.finished);if(!h.active&&!as.length)continue;total++;if(as.length)completed++;cats[h.game==='easy'||h.game==='medium'?'board':h.game].push(as.length?Math.max(...as.map(a=>Number(a.percent))):0)}let n=0,w=0;for(const [k,weight]of Object.entries({board:50,crossword:30,truth:20}))if(cats[k].length){n+=weight*cats[k].reduce((a,b)=>a+b,0)/cats[k].length;w+=weight}const p=w?n/w:null;return {percent:p,completed,total}}
 async function results(){await refresh();const visibleHomework=dash.homework.filter(h=>h.active||dash.attempts.some(a=>a.homework_id===h.id&&a.finished));const dates=[...new Set(visibleHomework.map(homeworkLesson))].sort().reverse();const initial=dates[0]||dateKey(lessonDate(new Date()));modal('Результаты',`<p class="school-muted">Выбери дату следующего урока литературы, к которому задана домашняя работа. В таблице останутся только задания, назначенные к этой дате. На телефоне список можно прокручивать по датам.</p><label class="results-date-label">Дата урока<select id="resultsLessonDate">${dates.length?dates.map(x=>`<option value="${x}" ${x===initial?'selected':''}>${esc(formatDate(x))}</option>`).join(''):`<option value="${initial}">${esc(formatDate(initial))}</option>`}</select></label><p class="school-muted">Лучшая завершённая попытка по каждому назначенному заданию. Бродилки — 50%, кроссворды — 30%, правда/ложь — 20%. Активное, ещё не выполненное задание — 0%; закрытое задание без результата не учитывается. Завершённые результаты сохраняются; эксперт не входит в итог.</p><p class="school-muted">5: от 85% · 4: от 70% · 3: от 55% · 2: от 40% · 1: от 25% · ниже: 0. Каждая ошибка учитывается.</p><div id="resultRows"></div>`);
  const render=()=>{const date=$('resultsLessonDate').value,homeworks=visibleHomework.filter(h=>homeworkLesson(h)===date),rows=dash.users.map(u=>{const a=aggregate(u,homeworks),assigned=homeworks.filter(h=>h.class===u.class),attempts=dash.attempts.filter(x=>x.account_id===u.id&&assigned.some(h=>h.id===x.homework_id));return `<details class="school-detail"><summary><b>${esc(u.name)} · ${esc(u.class)}</b> — ${a.percent===null?'Нет заданий':a.percent.toFixed(1)+'% · оценка '+grade(a.percent)} <small>(${a.completed}/${a.total} выполнено)</small></summary><div class="school-table"><table><thead><tr><th>Произведение / игра</th><th>Результат</th><th>Ошибки</th><th>Дата урока</th></tr></thead><tbody>${attempts.map(r=>{const h=assigned.find(h=>h.id===r.homework_id);return `<tr><td>${esc(h?titles[h.work]+' / '+games[h.game]:'Задание')}</td><td>${r.finished?Number(r.percent).toFixed(1)+'%':'В процессе'}</td><td>${r.wrong??0}</td><td>${esc(formatDate(date))}</td></tr>`}).join('')||'<tr><td colspan="4">Нет попыток по заданиям на эту дату.</td></tr>'}</tbody></table></div></details>`}).join('');$('resultRows').innerHTML=rows||'<p>Ученики ещё не зарегистрированы.</p>';if(!homeworks.length)$('resultRows').insertAdjacentHTML('afterbegin','<p class="school-muted">На эту дату домашние задания не назначались.</p>')};$('resultsLessonDate').onchange=render;render();
 }
 async function changePassword(){modal('Изменить пароль','<form id="pwForm"><label>Текущий пароль<input name="old" type="password" required autocomplete="current-password"></label><label>Новый пароль<input name="password" type="password" minlength="6" maxlength="128" required autocomplete="new-password"></label><button class="primary">Сохранить</button></form>');$('pwForm').onsubmit=async e=>{e.preventDefault();try{await api('password',Object.fromEntries(new FormData(e.target)));dialog.close()}catch(err){notice(err.message)}}}
 async function accounts(){await refresh();modal('Аккаунты учеников',`<p>Пароли не просматриваются: можно назначить новый. Смена данных или пароля завершает все сеансы ученика.</p>${classes.map(c=>'<span class="pill">'+c+': '+dash.users.filter(u=>u.class===c).length+'/15</span>').join(' ')}<div id="accountRows"></div>`);$('accountRows').innerHTML=dash.users.map(u=>`<div class="school-detail"><b>${esc(u.name)} · ${esc(u.class)}</b><button data-manage="${u.id}">Управлять</button></div>`).join('');dialog.querySelectorAll('[data-manage]').forEach(b=>b.onclick=()=>manage(dash.users.find(u=>u.id===b.dataset.manage)))}
 function manage(u){modal(u.name,`<label>Фамилия и имя<input id="amName" value="${esc(u.name)}" maxlength="100"></label><label>Класс<select id="amClass">${clsOptions()}</select></label><button id="amSave">Сохранить данные</button><label>Новый пароль<input id="amPassword" type="password" minlength="6" maxlength="128" autocomplete="new-password"></label><button id="amReset">Назначить пароль</button><label>Задание для сброса попыток<select id="amHomework">${dash.homework.filter(h=>h.class===u.class).map(h=>`<option value="${h.id}">${esc(titles[h.work]+' · '+games[h.game])}</option>`).join('')}</select></label><button id="amAttempts">Сбросить попытки задания</button><label>Завершённая попытка<select id="amAttempt">${dash.attempts.filter(a=>a.account_id===u.id&&a.finished).map(a=>{const h=dash.homework.find(h=>h.id===a.homework_id);return `<option value="${a.id}">${esc(h?titles[h.work]+' · '+games[h.game]:'Задание')} · ${a.percent}% · ${new Date(a.created_at).toLocaleString('ru')}</option>`}).join('')}</select></label><label>Исправленный процент<input id="amPercent" type="number" min="0" max="100" step="0.01"></label><button id="amScore">Исправить результат</button><hr><button id="amDelete">Удалить ученика</button>`);$('amClass').value=u.class;
  const op=async(operation,data)=>{await api('admin',{id:u.id,operation,...data});await accounts()};bind('amSave',()=>op('edit',{name:$('amName').value,class:$('amClass').value}));bind('amReset',()=>op('reset_password',{password:$('amPassword').value}));bind('amAttempts',async()=>{if($('amHomework').value&&confirm('Удалить все попытки ученика по выбранному заданию? Восстановить их через сайт нельзя.'))await op('reset_attempts',{homework:$('amHomework').value})});bind('amScore',()=>{if(!$('amAttempt').value||$('amPercent').value==='')throw Error('Выберите попытку и процент');return op('score',{attempt:$('amAttempt').value,percent:Number($('amPercent').value)})});bind('amDelete',async()=>{if(confirm('Удалить '+u.name+' вместе со всеми результатами? Это действие нельзя отменить.'))await op('delete',{})});
 }
 async function chooseGame(mode){await refresh();if(mode==='board'){modal('Выбери уровень',`<div class="school-row">${['easy','medium','expert'].map(g=>{const h=available(activeWork,g),ok=playable(h);return `<button data-school-level="${g}" class="${ok?'primary':'school-locked'}">${esc(games[g])}<span class="school-badge">${ok?'Доступен':'Не назначен / нет попыток'}</span></button>`}).join('')}</div>`);dialog.querySelectorAll('[data-school-level]').forEach(b=>b.onclick=()=>{const h=available(activeWork,b.dataset.schoolLevel);if(!playable(h)){locked(b);return}start(h).catch(e=>notice(e.message))})}else{const h=available(activeWork,mode);if(!playable(h))throw Error('Учитель ещё не открыл эту игру или попытки закончились');await start(h)}}
 async function start(h){if(busy)return;busy=true;try{const a=await api('start',{homework:h.id});attempt=a;selectedHW=h;dialog?.close();if(a.game==='truth'){show('truth');$('truthPlay').hidden=false;$('truthResult').hidden=true}else if(a.game==='crossword'){crosswordWords=a.grid.map(w=>({...w,word:'?'.repeat(w.length)}));ROWS=a.rows;COLS=a.cols;buildCrossword();restoreCross(a);show('crossword')}else{activeDifficulty=a.game;resetBoard();show('boardgame');if(document.documentElement.dataset.device==='phone')await enterBoardFullscreen()}await renderAttempt(a,false)}finally{busy=false}}
 function crossInputs(w){return Array.from({length:w.length},(_,j)=>document.querySelector(`#crossGrid input[data-key="${w.r+(w.d==='V'?j:0)},${w.c+(w.d==='H'?j:0)}"]`))}
 function restoreCross(a){if(a.words)a.grid.forEach((w,i)=>crossInputs(w).forEach((input,j)=>{if(input)input.value=a.words[i]?.[j]||''}));$('crossAnswers').hidden=true}
 const gameScreen={truth:'truth',crossword:'crossword',easy:'boardgame',medium:'boardgame',expert:'boardgame'};
 function ensureTimer(game){let badge=$('schoolTimer-'+game);if(badge)return badge;const screen=$(gameScreen[game]),head=screen?.querySelector('.game-head');if(!head)return null;badge=document.createElement('span');badge.id='schoolTimer-'+game;badge.className='pill school-game-timer';badge.setAttribute('role','timer');badge.setAttribute('aria-label','Оставшееся время');head.append(badge);return badge}
 function clock(ms){const seconds=Math.max(0,Math.ceil(ms/1000));return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')}
 function runTimer(a){clearInterval(timerHandle);timerExpired=false;timerDeadline=performance.now()+Math.max(0,a.remainingMs||0);const badge=ensureTimer(a.game);if(!badge)return;const paint=()=>{const left=Math.max(0,timerDeadline-performance.now());badge.textContent='Осталось: '+clock(left);badge.classList.toggle('school-time-urgent',left<60000);if(left<=0&&current===gameScreen[a.game]&&!timerExpired&&!a.finished&&!busy){timerExpired=true;const data=a.game==='crossword'?{words:a.grid.map(w=>crossInputs(w).map(input=>input?.value||'').join(''))}:{};play('timeout',data).catch(e=>notice(e.message))}};paint();timerHandle=setInterval(paint,250)}
 async function renderAttempt(a,animate){
  if(a.game==='truth'){$('truthCounter').textContent=`${Math.min(a.index+1,10)} / 10`;$('truthProgress').style.width=(a.index*10)+'%';if(a.question)$('factText').textContent=a.question.text;$('truthFeedback').textContent='';$('truthFeedback').className='feedback';document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=false;b.classList.remove('school-answer-correct','school-answer-wrong')})}
  else if(a.game==='crossword'){if(a.statuses){document.querySelectorAll('#clues li').forEach((li,i)=>{li.classList.toggle('word-good',a.solved.includes(i));li.classList.toggle('word-bad',!a.solved.includes(i))});a.grid.forEach((w,i)=>crossInputs(w).forEach(input=>{if(!input)return;const owned=a.grid.some((other,j)=>a.solved.includes(j)&&crossInputs(other).includes(input));input.disabled=owned;input.closest('.cross-cell').classList.toggle('good',owned);input.closest('.cross-cell').classList.toggle('bad',!owned)}));$('crossFeedback').textContent=`Правильно слов: ${a.correct}. Ошибок: ${a.wrong}. Исправление не стирает ошибки.`}}
  else{document.querySelectorAll('.difficulty-btn').forEach(b=>{b.classList.toggle('active',b.dataset.difficulty===a.game)});boardPoints=a.correct;wrongAnswers=a.wrong;rolling=true;$('rollBtn').disabled=true;if(animate){if(a.dice){$('dice').textContent=['⚀','⚁','⚂','⚃','⚄','⚅'][a.dice-1];await showDiceRoll(a.dice)}for(const move of a.moves){position=move.from;if(move.portal)await teleportTo(move.to,'Портал');else await moveTokenBy(move.to-move.from,move.to<move.from?'Назад':'Ход')}}position=a.position;renderToken();rolling=false;$('rollBtn').disabled=!!a.question||a.finished;$('boardReset').textContent='Завершить';$('boardStatus').textContent=a.finished?'Игра завершена':a.question?'Ответь на вопрос':a.position===4?'Подсказка: следующий вопрос с двумя вариантами':a.position===24?'Ещё бросок!':'Можно бросать кубик';if(a.question&&!a.finished)boardQuestion(a)}
  if(a.finished){clearInterval(timerHandle);timerHandle=null;$('questionDialog').close();await exitBoardFullscreen();await refresh();const isBoard=!['truth','crossword'].includes(a.game);modal(a.timedOut?'Время вышло':a.won===false?'Игра завершена':isBoard?'Ты добрался до финиша!':'Задание выполнено',`<p>Правильных ответов: <b>${a.correct}</b>. Ошибок: <b>${a.wrong}</b>.</p><h3>${Number(a.percent).toFixed(1)}%${a.game==='expert'?' · эксперт, без итоговой оценки':' · оценка '+grade(Number(a.percent))}</h3><p>Результат сохранён.</p><button class="primary" id="attemptDone">К произведению</button><button id="attemptAgain">Ещё попытка</button>`,`school-result ${isBoard?{easy:'bronze',medium:'silver',expert:'gold'}[a.game]:''}`);bind('attemptDone',()=>{dialog.close();attempt=null;show('book');locks()});bind('attemptAgain',async()=>{const h=available(selectedHW.work,selectedHW.game);if(!playable(h))throw Error('Попытки закончились');await start(h)});$('rollBtn').disabled=true}else runTimer(a)
 }
 function boardQuestion(a){const dlg=$('questionDialog');$('questionText').textContent=a.question.text;$('questionMeta').textContent=games[a.game]+' · вопрос '+(a.index+1);$('questionFeedback').textContent='';$('questionFeedback').className='feedback';$('questionOptions').innerHTML='';a.question.choices.forEach((c,i)=>{const b=document.createElement('button');b.className='option';b.dataset.answerId=c.id;b.textContent=['А. ','Б. ','В. ','Г. '][i]+c.label;b.onclick=()=>play('answer',{answer:c.id},b);$('questionOptions').append(b)});if(!dlg.open)dlg.showModal()}
 async function play(operation,data={},source=null){if(busy||!attempt||attempt.finished)return;busy=true;const old=attempt;$('rollBtn').disabled=true;document.querySelectorAll('#questionOptions button,[data-answer]').forEach(b=>b.disabled=true);try{const next=await api('play',{id:old.id,revision:old.revision,operation,...data});const receivedAt=Date.now();attempt=next;if(operation==='answer'&&next.right!=null){source?.classList.add(next.right?'school-answer-correct':'school-answer-wrong');const feedback=old.game==='truth'?$('truthFeedback'):$('questionFeedback');feedback.textContent=next.right?'Верно!':'Неверно. Ошибка учтена.';feedback.className='feedback '+(next.right?'ok':'bad');if(old.game==='truth')await new Promise(r=>setTimeout(r,900));else{if(next.answerReview){document.querySelectorAll('#questionOptions button').forEach(b=>{if(Number(b.dataset.answerId)===next.answerReview.correctId)b.classList.add('school-answer-correct')});feedback.textContent+=(next.right?'':' Правильный ответ: '+next.answerReview.text);}await waitBoardReview($('questionDialog'))}}else if(operation==='answer'&&old.game!=='truth'){$('questionFeedback').textContent='Ответ уже сохранён.';await new Promise(r=>setTimeout(r,500))}if(operation==='answer'&&old.game!=='truth')$('questionDialog').close();next.remainingMs=Math.max(0,next.remainingMs-(Date.now()-receivedAt));await renderAttempt(next,next.revision!==old.revision)}catch(e){notice(e.message);await renderAttempt(old,false)}finally{busy=false}}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!user||staff())return;const intercept=()=>{e.preventDefault();e.stopImmediatePropagation()};
  if(b.matches('[data-work]')){if(!Object.keys(games).some(g=>playable(available(b.dataset.work,g)))){intercept();locked(b);return}setTimeout(locks,0)}
  if(b.matches('[data-start]')){intercept();if(b.classList.contains('school-locked')){locked(b);return}chooseGame(b.dataset.start).catch(e=>notice(e.message));return}
  if(b.matches('.difficulty-btn')){intercept();if(attempt&&!attempt.finished){notice('Заверши текущую попытку или выйди к произведению, чтобы выбрать другую игру.');return}chooseGame('board').catch(e=>notice(e.message));return}
  if(b.id==='rollBtn'){intercept();play('roll');return}
  if(b.matches('[data-answer]')){intercept();play('answer',{answer:b.dataset.answer==='true'},b);return}
  if(b.id==='crossCheck'){intercept();if(attempt)play('check',{words:attempt.grid.map(w=>crossInputs(w).map(i=>i?.value||'').join(''))});return}
  if(b.id==='crossAnswers'||b.id==='crossReset'){intercept();return}
  if(['boardReset','truthAgain','winAgain','lossAgain'].includes(b.id)){intercept();if(attempt&&!attempt.finished){if(confirm('Завершить попытку без результата? Она будет потрачена и получит 0%.'))play('abandon')}else chooseGame(b.id==='truthAgain'?'truth':'board').catch(e=>notice(e.message));return}
  if(b.id==='backBtn'){if(busy){intercept();return}setTimeout(()=>refresh().catch(()=>{}),0)}
 },true);
 // Refresh access after returning to the page; never trust a locally selected role.
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&user&&!busy)refresh().catch(()=>{})});
 window.addEventListener('pageshow',e=>{if(e.persisted)location.reload()});
 if(token)enter().catch(e=>{token='';clearToken();gate('student',e.message)});else gate();
})();

